"""create games and rating_snapshots

Revision ID: a371a055324b
Revises: 
Create Date: 2026-09-29 13:54:24.030827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a371a055324b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('platforms', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('steam_app_id', sa.Integer(), nullable=True),
    sa.Column('opencritic_id', sa.Integer(), nullable=True),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id'),
    sa.UniqueConstraint('opencritic_id'),
    sa.UniqueConstraint('steam_app_id')
    )
    op.create_index(op.f('ix_games_title'), 'games', ['title'], unique=False)
    op.create_table('rating_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('steam', 'opencritic', 'igdb', name='ratingsource', native_enum=False, length=32), nullable=False),
    sa.Column('audience', sa.Enum('critic', 'fan', name='ratingaudience', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_rating_snapshots_score_range'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rating_snapshots_game_fetched', 'rating_snapshots', ['game_id', 'fetched_at'], unique=False)
    op.create_index('ix_rating_snapshots_game_source_audience', 'rating_snapshots', ['game_id', 'source', 'audience'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rating_snapshots_game_source_audience', table_name='rating_snapshots')
    op.drop_index('ix_rating_snapshots_game_fetched', table_name='rating_snapshots')
    op.drop_table('rating_snapshots')
    op.drop_index(op.f('ix_games_title'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
